//! PNG decoding through the TV's own `libpng16`, `dlopen`'d like every other
//! device library here (docs/device.md).
//!
//! Why PNG and not the JPEG the server would rather send: the TV ships
//! `libjpeg.so.62` and this development machine ships `libjpeg.so.8`. Those are
//! different ABIs for the same name, and libjpeg's entry points take a struct
//! whose layout is part of that ABI, so a `dlopen`'d JPEG path would need one
//! transcribed struct per version and would be wrong on whichever machine it
//! was not written for. `libpng16.so.16` is on both (1.6.39 on the TV, 1.6.58
//! here) and Jellyfin re-encodes to PNG on request, so one decoder covers both.
//!
//! This uses libpng's *simplified* API, which is the reason the binding is
//! this small: `png_image` is a fixed, version-checked struct, the three calls
//! below are the whole interface, and none of it uses `setjmp` -- errors come
//! back as a zero return and a message in the struct. The classic
//! `png_create_read_struct` path would need `setjmp`, which Zig cannot provide.
//!
//! See docs/images.md.

const std = @import("std");
const c = std.c;

/// `PNG_IMAGE_VERSION`. `png_image_begin_read_*` rejects anything else, which
/// is what makes this struct safe to declare without libpng's headers.
const image_version = 1;
/// `PNG_FORMAT_RGB`: the colour flag, no alpha, no colormap, 8 bits a channel.
const format_rgb = 0x02;

/// `png_image`, verbatim from png.h 1.6. Stable since 1.6.0 by design -- the
/// `version` field exists so that this declaration can be checked at runtime.
const PngImage = extern struct {
    opaque_ptr: ?*anyopaque = null,
    version: u32 = image_version,
    width: u32 = 0,
    height: u32 = 0,
    format: u32 = 0,
    flags: u32 = 0,
    colormap_entries: u32 = 0,
    warning_or_error: u32 = 0,
    message: [64]u8 = @splat(0),
};

var library: ?*anyopaque = null;
var beginReadFromMemory: *const fn (*PngImage, [*]const u8, usize) callconv(.c) c_int = undefined;
var finishRead: *const fn (*PngImage, ?*const anyopaque, [*]u8, i32, ?*anyopaque) callconv(.c) c_int = undefined;
var freeImage: *const fn (*PngImage) callconv(.c) void = undefined;
var accessVersionNumber: *const fn () callconv(.c) u32 = undefined;

pub const Image = struct {
    width: u32,
    height: u32,
    /// `width * height * 3` bytes from the caller's allocator.
    rgb: []u8,
};

pub const Error = error{ NoLibPng, DecodeFailed, OutOfMemory };

/// Resolve libpng once. Safe to call from any thread before the workers start;
/// after that it is read-only.
pub fn init() Error!void {
    if (library != null) return;
    // `libpng16.so.16` and not `libpng.so`: the unversioned symlink is a
    // development-package file and the TV has no development packages.
    const handle = c.dlopen("libpng16.so.16", .{ .NOW = true }) orelse return error.NoLibPng;
    inline for (.{
        .{ "png_image_begin_read_from_memory", &beginReadFromMemory },
        .{ "png_image_finish_read", &finishRead },
        .{ "png_image_free", &freeImage },
        .{ "png_access_version_number", &accessVersionNumber },
    }) |entry| {
        entry[1].* = @ptrCast(@alignCast(c.dlsym(handle, entry[0]) orelse return error.NoLibPng));
    }
    library = handle;
    const version = accessVersionNumber();
    std.debug.print("libpng {d}.{d}.{d}\n", .{ version / 10000, version / 100 % 100, version % 100 });
}

/// Decode `data` to tightly packed RGB8. The result is owned by `allocator`.
pub fn decode(allocator: std.mem.Allocator, data: []const u8) Error!Image {
    if (library == null) return error.NoLibPng;
    var png: PngImage = .{};
    if (beginReadFromMemory(&png, data.ptr, data.len) == 0) return error.DecodeFailed;
    // From here libpng holds an allocation inside `png`, released either by
    // `png_image_finish_read` or explicitly.
    errdefer freeImage(&png);

    png.format = format_rgb;
    const size = @as(usize, png.width) * png.height * 3;
    if (size == 0) return error.DecodeFailed;
    const rgb = try allocator.alloc(u8, size);
    errdefer allocator.free(rgb);
    // row_stride 0 means "tightly packed", which is what the texture upload
    // wants; no colormap and no background, since the format has no alpha.
    if (finishRead(&png, null, rgb.ptr, 0, null) == 0) return error.DecodeFailed;
    return .{ .width = png.width, .height = png.height, .rgb = rgb };
}

test "decodes a filtered RGB png through libpng" {
    init() catch return error.SkipZigTest;
    // A real encoder picked the filters here, so this exercises more than the
    // None path. Generated by tools/make-test-png.py.
    const png = @embedFile("testdata/gradient.png");
    const decoded = try decode(std.testing.allocator, png);
    defer std.testing.allocator.free(decoded.rgb);
    try std.testing.expectEqual(@as(u32, 16), decoded.width);
    try std.testing.expectEqual(@as(u32, 16), decoded.height);
    for (0..16) |y| for (0..16) |x| {
        const pixel = decoded.rgb[(y * 16 + x) * 3 ..][0..3];
        try std.testing.expectEqual(@as(u8, @intCast(x * 16)), pixel[0]);
        try std.testing.expectEqual(@as(u8, @intCast(y * 16)), pixel[1]);
        try std.testing.expectEqual(@as(u8, 64), pixel[2]);
    };
}
